README.md

Tooltip.js isn't powered by Tether, but by Popper.js
https://www.npmjs.com/package/tooltip.js

Use correct URL for Tooltip.js

---

README.md

Minor changes:
* Corrected v-tooltip modifier from `bottom-left` to `bottom-start`
* Mentioned auto options for placement under Popover Component Reference. If this feature isn't ready yet, that's okay. It just seemed to work for me so I thought others should know that it's available.

Updated placement documentation in readme

---

.npmignore

More and more npm packages contain ES2015+ code.
As discussed in [this AMA](https://github.com/sindresorhus/ama/issues/446), this causes a lot of troubles (Uglify and old browsers) for people.
One possible solution is to transpile external dependencies, as discussed in [this issue on create-react-app](https://github.com/facebookincubator/create-react-app/issues/1125) and implemented in [this pull request](https://github.com/facebookincubator/create-react-app/pull/3776).
This doesn't currently work with v-tooltip as the .babelrc file is published on npm.
Here is a [small repo demonstrating the bug](https://github.com/oligot/v-tooltip-babelrc).
Running `npm run build` results in this error
```
ERROR in ./node_modules/v-tooltip/dist/v-tooltip.esm.js
Module build failed: Error: Couldn't find …
```

Don't publish .babelrc file

---

demo-src/src/App.vue
src/components/Popover.vue

Fix z-index of popover arrow.
Reproduce problem:
Add box-shadow to popover inner and arrow goes under shadow if you don't add z-index for it.
Fix:
Place arrow after inner block -> you dont need use z-index.

Arrow z-index

---

src/components/Popover.vue
src/lib/tooltip.js

Getting the target for mouseleave in popovers and tooltips was only working on Chrome. It looks like it was a bug in tooltip.js that was eventually fixed. Pretty small change.
Relevant MDN: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget
Relevant line in tooltip.js: https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L404

Fix getting related reference/target on mouseleave

---

src/components/Popover.vue

Hi there! This is just a simple fix for #79. Popper.js allows either a string or an element for this. Please let me know if this PR needs anything else.

Add `String` to `boundariesElement` prop allowed types

---

src/lib/tooltip.js

The objective is consistency with the rest of the code.
I stumbled into this problem when wanting to use the unbundled library, in order to avoid duplicating shared dependencies (poppers.js), by directly importing `v-tooltip/src/index.js`. The bundler of the module I wanted to fix stumbles upon the arrow functions as class properties.

Transform arrow functions into class methods

---

src/lib/tooltip.js

When the classes of the v-tooltip instruction are passed in the form of an array, the tooltip flashes.

fix:  When the classes of the v-tooltip instruction are passed in the form of an array, the tooltip flashes.

---

types/index.d.ts

Solution to the error:
`3:1 Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.`
Issue: #459

Fix to 'Top-level declarations' error

---

src/lib/tooltip.js

This change attempts to fix some alerts that have been received where
`popperInstance` is `undefined`, but we try to access methods on it.

Add guards for `popperInstance`

---

README.md

Update README.me to describe the property value. 
According to the current implementation, which is described on #127 and #368 , a `false` value is also allowed on `container` property. It will append the popover on target parent node.

Describe `false` value on container property

---

src/components/Popover.vue

Maybe out of the scope of what this library wants to achieve but I find it useful to be able to grab this via the slot & not have to keep a local copy of the open state

Expose isOpen in the popover slot

---

packages/v-tooltip/nuxt.mjs
packages/v-tooltip/package.json
yarn.lock

To prevent any issues, we'd advise not to rely on an implicit `@nuxt/kit` dependency. This PR converts the module to a non-kit module; we can upgrade later when ready (and as it's an SDK we'd recommend including kit in your dependencies at that point).

refactor: remove kit dependency

---

packages/v-tooltip/src/components/Popper.js

fix: "this is null" in Popper.js

---

packages/v-tooltip/src/components/Popper.js

This resolves #817 by having the watch on triggers do nothing if $_events isn't an array, since that means init hasn't been run yet and when it is it will do what's needed.

fix: ignore triggers watch before init has been run on mounted

---

packages/docs/src/guide/directive.md

This fixes a typo I stumbled upon, closes https://github.com/Akryum/floating-vue/issues/849

docs: Correct typo in documentation

---

README.md

it was a relative link otherwise

docs: fix floating-ui.com link

---

packages/docs/src/guide/css.md

I fix typo in [CSS guide](https://floating-vue.starpad.dev/guide/css.html#advanced-transitions).

docs: typo

---

packages/floating-vue/package.json

Removes unnecessary files from published package.
The latest `2.0.0-beta.20` includes sources, test files and configuration files: https://unpkg.com/browse/floating-vue@2.0.0-beta.20/
<details>
<summary>Before</summary>
```sh
$ npm pack --dry-run
npm notice 📦  floating-vue@2.0.0-beta.20
npm notice === Tarball Contents === 
npm notice 1.3kB  .eslintrc.js                             
npm notice 1.1kB  LICENSE                                  
npm notice 867B   README.md                                
npm notice 211B   babel.config.js                          
npm notice 714B   dist/components/Dropdown.vue.d.ts        
npm notice 714B   dist/components/Menu.vue.d.ts            
npm notice 11.2kB dist/components/Popper.d.ts              
npm notice 12.4kB dist/components/Popper.vue.d.ts …
```

build: exclude sources from published package

---

packages/floating-vue/nuxt.mjs

This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.

fix: import nuxt composables from #imports

---

docs/migration/migration-from-v2.md

This PR fixes a spelling mistake in the docs. The word "positionning " has been corrected to "positioning " in the [migration-from-v2.md file](../blob/main/docs/migration/migration-from-v2.md#floating-ui).

docs: Fixed spelling mistake in migration v2 docs

---

src/components/Popover.vue

I needed to change the event, with which the popover component is closed when the user clicks outside. Instead of listening to `click`, with this change it listens to `mousedown` now.
The reason for that is that if you open the popover, then drag the window with the scrollbar, it will only close the popover *after* releasing the scrollbar.

feat: close the popover on `mousedown` instead of `click`

---

packages/floating-vue/src/components/PopperContent.vue

This PR fixes the reported console error that also results auto-hiding when clicking inside the hover menu
https://github.com/Akryum/floating-vue/issues/1059

fix: prevent aria-hidden on focusable elements
